#  Template NodeJS Web Application for Azure Web App service

#  This template allows you to deploy your NodeJS web application to Azure Web App Service.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The NodeJS application will be validated after the code is merged to master and deployment can be triggered manually.

# Prerequisites: $$AZURE_APP_ID, $AZURE_PASSWORD, $AZURE_TENANT_ID, $AZURE_RESOURCE_GROUP, $AZURE_APP_NAME setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/microsoft/azure-web-apps-deploy/src/1.0.3/README.md


image: php:7.4.3

pipelines:
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip
              - apt-get install -y openssh-client
              - ssh root@142.93.213.85 'bash -s' < execute.sh